### ISSUE TITLE
Copy Project from Frontend Edit

### ISSUE THREAD

**Issue by oraclerob** [upstreamplugin/UpStream-Copy-Project#17]
We would like to be able to copy projects from the frontend edit screen. One of the big problems with the Copy Project plugin is that we have to give dashboard access in the backend to our users.  This is not ideal as these users need to be admin users and we have blocked non admin users from the backend for security reasons.

I've already started work on this and almost got a prototype working, this would be a handy feature.

**Comment by stevejburge** [comment]
Thanks @oraclerob. 

We really appreciate the help. 

Some background - when we took over UpStream, it was mostly admin area extension. 

We think that users prefer to use the frontend so we're slowly migrating all the features to the frontend. However, some features (such as Copy Project) aren't there yet,

**Comment by oraclerob** [comment]
Development has been completed and tracked in https://github.com/upstreamplugin/UpStream-Frontend-Edit/issues/128
